# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = "my-pins")
v <- vetiver_pin_read(b, "burnout-risk-xgb", version = "20250630T202924Z-6d67f")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
